### ISSUE TITLE
Unable to create plugin: replaces must be an array.

### ISSUE THREAD

**Issue by AdrienAdB** [wintercms/wn-builder-plugin#12]
Hi,
On a fresh WinterCMS and Builder plugin install, I am unable to create plugin with the builder.

"The replaces must be an array"

Builder v2.0.1

**Comment by AdrienAdB** [comment]
Below change did the fix:

https://github.com/wintercms/wn-builder-plugin/blob/main/classes/PluginBaseModel.php#L31

```php
   public $replaces = [];
```

**Comment by LukeTowers** [comment]
@AdrienAdB can you submit that in a PR?
