### ISSUE TITLE
updates/version.yaml needs to be updated with 2.0.2 changelog

### ISSUE THREAD

**Issue by arvislacis** [wintercms/wn-builder-plugin#18]
File `updates/version.yaml` needs to contain entry for 2.0.2 version so current version of plugin is not determined as 2.0.1 (in back-end plugin section etc.).

**Comment by bennothommo** [comment]
Thanks @arvislacis - updated the version file. https://github.com/wintercms/wn-builder-plugin/commit/fd37fc5f661ad93fb0e2c545ff380634d614ddf8
