### ISSUE TITLE
Open list of plugins automatically if no plugin is selected

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/wn-builder-plugin#25]
Just a quick suggestion, instead of (or in addition to) displaying this:

![image](https://user-images.githubusercontent.com/901732/154786732-2d79bab4-ea7a-4af8-9179-3e237da820ed.png)

Just open the menu up automatically if no plugin is selected on when the page is loaded.

**Comment by bennothommo** [comment]
I think this might be a little too jarring to happen on page load, as opening the plugin menu shifts the layout.

What are your thoughts on simply having some more prominent buttons to "Create a plugin" or "Browse plugins" instead of the simple instruction shown above?

**Comment by multiwebinc** [comment]
@bennothommo The only problem I see with that is the UI for opening up the side menu is rather hidden and probably not very intuitive, so people might not how to switch plugins. How hard is it to hide the left menu for a specific page? Here's just a quick brainstorming idea, but we could create a page like:

![image](https://user-images.githubusercontent.com/901732/157524638-c3843244-02a8-4739-88db-125779bdcb4c.png)

When no plugin is selected, this will be displayed. Then when the user selects a plugin, they get the current view with a link to switch plugins:

![image](https://user-images.githubusercontent.com/901732/157524856-f5d1e0db-59e0-480a-a614-917fe0616f1e.png)

When a user clicks the switch plugin button, the currently selected plugin is removed from the session cookie (or wherever it's stored).

**Comment by LukeTowers** [comment]
That looks pretty good @multiwebinc!

**Comment by bennothommo** [comment]
@multiwebinc Love the mockup :)

I think that's doable - the only extra thing we need to consider is that there is an option in the plugins list to show plugins that *were not* created with the Builder plugin, so we'd need a comparable filter or option with this new "splash" page.
