### ISSUE TITLE
Custom database types not recognized.(Referencing an older issue on rainlab builder)

### ISSUE THREAD

**Issue by tschallacka** [wintercms/wn-builder-plugin#26]
See for orinal issue https://github.com/rainlab/builder-plugin/issues/257

See if this can be implemented automatically in schemabuilder or somewhere else.

Aparently this solves it.

Db::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('txid_snapshot', 'text');

I'll pick this up if nobody else does, and otherwise this adds an existing issue that can be referenced.

**Comment by LukeTowers** [comment]
I'm not sure what this plugin would do differently, it sounds like adding support for custom doctrine type mapping is already supported through using your own plugins to register it to the global schema manager?

**Comment by tschallacka** [comment]
If you look at the original issue, you'll see that although its registered, an error message would stil popup. 
So somewhere there was an issue with it still, when using non standard schema input types.

I'll see if this is still an issue in wintercms/laravel 9.
I just ported this issue here, to see if its still an issue and if I can fix it, or at least add to the documentation, for those who encounter it how to resolve it.

**Comment by bennothommo** [comment]
@tschallacka feel free to provide some edits for the docs, if the suggested fix works. I'll close this for now.
