### ISSUE TITLE
Error adding permissions 

### ISSUE THREAD

**Issue by faselunare** [wintercms/wn-builder-plugin#32]
Step to reproduce
Go to permission tabs
Add permission like

```
conference.event.create | base33.conference::lang.conference.events.event | base33.conference::lang.conference.events.event_create
```

before save, translations are added in the lang.php file
``` 
<?php return [
    'plugin' => [
        'name' => 'Conference',
        'description' => 'Events management plugin',
    ],
    'conference' => [
        'events' => [
            'event' => 'Event',
            'event_create' => 'Create',
        ],
    ],
];
```
while saving I get this error
<img width="646" alt="Screenshot 2022-03-16 at 20 28 05" src="https://user-images.githubusercontent.com/39338657/158674994-d92cd570-71d7-46cb-bb40-64603582e66c.png">

and is impossible to save permission

**Comment by faselunare** [comment]
While this code is present in the lang.php file 
``` 
'conference' => [
        'events' => [
            'event' => 'Event',
            'event_create' => 'Create',
        ],
    ],
    
  ```
  
  I get this other error
  ``` 
  htmlspecialchars(): Argument #1 ($string) must be of type string, array given
/Users/francesco/Dev/sites/wn-conference/vendor/winter/storm/src/Support/helpers.php line 23
```

system.log is empty, no stack trace available

**Comment by faselunare** [comment]
After an investigation, seems that when creating a new string, you can't have something like this
```
base33.conference::lang.event.event_create
```

but just
``` 
base33.conference::lang.event_create
```

in the preview version of builder
string like this

```
base33.conference::lang.event.opening
 ```
 works fine
 
 see an old piece of code that works
 ```
<?php return [
    'plugin' => [
        'name' => 'Conference',
        'description' => '',
    ],
    'event' => [
        'opening' => 'Opening',
        'closing' => 'Closing',
    ],
    ... 
    ```

**Comment by bennothommo** [comment]
@faselunare I can't replicate this, even with the steps you've added above. You may need to do some more investigation and see if you can narrow it down somewhere.

**Comment by faselunare** [comment]
Ok, the same error happened when creating backend menu 
![image](https://user-images.githubusercontent.com/39338657/158786263-564883f2-c29e-4616-9384-2f8a7adee2bb.png)

Create a new menu's voice
add a code with 'something.somethingelse' and get the error

**Comment by bennothommo** [comment]
@faselunare can you please post your entire lang file(s)? I cannot replicate the above either.

**Comment by faselunare** [comment]
this is one lang file from another smallest plugin i'm working on

```
<?php return [
    'plugin' => [
        'name' => 'Exhibition Catalog',
        'description' => 'Create a catalog of exhibition elements, for example: exhibition spaces, artwork... end with a form for request informations about the selected products.',
    ],
    'forms' => [
        'reorder' => 'Reorder',
    ],
    'title' => 'Title',
    'slug' => 'Slug',
    'description' => 'Description',
    'parent' => 'Parent',
    'isactive' => 'Is active',
    'excat' => 'Exhibition Catalog',
    'create' => 'Create',
    'excat_categories' => 'Exhibition Catalog Categories',
    'select_parent' => 'Select parent category',
    'media' => 'Media',
    'content' => 'Content',
    'image' => 'Image',
    'gallery' => 'Gallery',
    'active' => 'Active',
    'assets' => 'Assets',
    'items' => 'Items',
    'categories' => 'Categories',
    'price' => 'Price',
    'test' => [
        'active' => 'test active',
    ],
    'permission' => [
        'edit_category' => 'Edit category',
    ],
];
```

now seems to work when i use a string like base33.excat::lang.permission.edit

**Comment by bennothommo** [comment]
@faselunare so you're no longer experiencing the issue?

**Comment by faselunare** [comment]
no

**Comment by bennothommo** [comment]
Thanks @faselunare. Please let me know if the issue reoccurs and we'll reopen.
