### ISSUE TITLE
mb_strtolower(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by moedayraki** [wintercms/wn-builder-plugin#40]
## Summary: 
On creating the first new table in a custom plugin, an unhandled error occured.

## Installed build and plugins: 
Winter CMS Build: 1.2.0
Plugins Installed: Demo, Builder

## Reproduce steps: 
-create a new plugin and call it 'Menus'
-create a new table 'menus_list'

Expected behavior: 
-Save the table
-Go back to Builder page

## Actual behavior:
Unhandled Error

```
mb_strtolower(): Argument #1 ($string) must be of type string, array given
../vendor/laravel/framework/src/Illuminate/Support/Str.php line 474
```

P.S: I'm new to the CMS so I might be doing something wrong but it was a straight forward thing. Create Plugin->Add new Table->Error

**Comment by LukeTowers** [comment]
@moedayraki can you post the full stack trace for the error here?

**Comment by bennothommo** [comment]
I'm unable to replicate this. The failure could be happening somewhere else.

@moedayraki please provide a full stack trace, and we'll reopen.
