### ISSUE TITLE
RainLab.Builder conflicts

### ISSUE THREAD

**Issue by lucianomelotti** [wintercms/wn-builder-plugin#5]
In a new project with no plugin installed, when I install the plugin I get a message:

**Some issues have been detected and require attention:
The Winter.Builder plugin replaces RainLab.Builder, please remove RainLab.Builder to ensure there are no conflicts**

but the RainLab.Builder plugin is not installed

**Comment by LukeTowers** [comment]
This is a known issue with 1.1.3, already been fixed on the develop branch and will be fixed in 1.1.4 once that's ready to be released.
