### ISSUE TITLE
failed database version upgrade 

### ISSUE THREAD

**Issue by SledgehammerPL** [wintercms/wn-builder-plugin#53]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

PostgreSQL

### Plugins installed

Builder

### Issue description

I changed the column (e.g. drop) AND change name of table and tried to apply this upgrade to other system.

But i have some view which forbid to apply patch - but the name of table was changed. This shouldn't work like this. All or nothing. If it break - it should be still old name of table.

### Steps to replicate

Changed the column (e.g. drop) AND change name of table and tried to apply this upgrade to other system.

### Workaround

I have to change manually name of table and apply patch again

**Comment by bennothommo** [comment]
I have been unable to replicate this with the latest version of the Builder plugin. Please feel free to re-open if the issue persists.
