### ISSUE TITLE
Long list of permission doesn't scroll

### ISSUE THREAD

**Issue by faselunare** [wintercms/wn-builder-plugin#58]
When you create plugin permissions, if the list is very long, it doesn't scroll and therefore you can't see them. If I add them by hand in the plugin.yaml they work but I can't see them.

**Comment by bennothommo** [comment]
Fixed as of https://github.com/wintercms/wn-builder-plugin/commit/2d4ab1bc74a993c38f52a9d37c882131c5ff8bb4
