### ISSUE TITLE
In the database tab, none of the checkboxes can be unchecked

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/wn-builder-plugin#59]
None of the checkboxes in the database editor (e.g. unsigned, nullable, autoincr, pk) can be unchecked once they are checked. Clicking them does nothing once they are already checked.

**Comment by bennothommo** [comment]
I am unable to replicate this on the current version of the Builder plugin. If you are able to provide instructions for replicating it on the current version, please let me know and we'll reopen this.
