### ISSUE TITLE
Field search not working

### ISSUE THREAD

**Issue by WebProviderNGO** [wintercms/wn-builder-plugin#60]
v2.0.6, SQLite.
For one field of type Text in columns.yaml, I set the search capability. As a result, the search is performed on two letters in the second word.

**Comment by bennothommo** [comment]
@WebProviderNGO would you mind providing more context please? Maybe some screenshots and what was specifically entered so we can try and replicate.

**Comment by bennothommo** [comment]
Closing for now, as there has been no further updates on this issue. Please feel free to get in touch with us if there's still an issue and we'll re-open.
