### ISSUE TITLE
After deleting a column, the table is deleted

### ISSUE THREAD

**Issue by WebProviderNGO** [wintercms/wn-builder-plugin#61]
Winter 1.2.1, Builder 2.0.6, MySQL 5.7.27, PHP 8.2

I have created a boolean column. Added records using this column. Then he deleted the boolean column, but at the same time the table in which there was a boolean column was deleted.

What else can I do to confirm the mistake and help others fix it?

**Comment by bennothommo** [comment]
The Builder plugin only creates and runs migrations to modify the database, it wouldn't delete the table out of the blue unless someone created a migration to drop the table. Did the migrations perhaps fail to run? You should be able to verify this in your logs or via the `system_plugin_history` table in your database.

**Comment by bennothommo** [comment]
We haven't heard back so we'll close this issue for now. If the issue persists, please provide some more information and we'll re-open.
