### ISSUE TITLE
Cant access to builer page

### ISSUE THREAD

**Issue by zimbar** [wintercms/wn-builder-plugin#62]
Hello,

I have installed the module on wintercms version 1.2.1 and php 8.1.17.

I removed cms module from "loadModules" and i set 'backendUri' => ''  in  config/cms.php,.

When I click on the "builder" menu, I have this error

"We searched and searched but the requested URL just couldn't be found. Perhaps you were looking for something else?

http://127.0.0.1:8000/winter/builder"

Thanks

**Comment by bennothommo** [comment]
Hi @zimbar,

I've replicated the same setup and the Builder plugin worked perfectly for me, so there might be something else at play here.

<img width="1913" alt="Screenshot 2023-04-21 092808" src="https://user-images.githubusercontent.com/15900351/233519390-6cc045f4-c4e7-4b7b-9319-5959f42155b2.png">

You could try clearing your cache with `php artisan cache:clear`, and maybe look at if your server is doing URL rewrites correctly.

**Comment by zimbar** [comment]
Hi @bennothommo 

Thanks, i will try again

**Comment by bennothommo** [comment]
@zimbar I haven't heard back so I'll assume all is OK. Please let us know if there's further issues and we'll re-open.
