### ISSUE TITLE
Version file %s is not found when try to access migration in subdir

### ISSUE THREAD

**Issue by dimti** [wintercms/wn-builder-plugin#63]
If create migration file with artisan command `./artisan create:migration plugin.code --name "SomeMigration" --table some_table -u` then created migration in subdir with dirname as version number.
On the builder plugin if try to open this migration from the list - catching appliaction error about unable to find migration file

**Comment by dimti** [comment]
Simple fix there: https://github.com/dimti/wn-builder-plugin/commit/e323ec72

**Comment by LukeTowers** [comment]
@bennothommo are you able to take 15 minutes to look at this? It should be a simple fix

**Comment by dimti** [comment]
May be is not fully correctly fix, because after create migrations from wn-builder - migration file path prefixed with current dir `./`
![image](https://github.com/wintercms/wn-builder-plugin/assets/582144/c2b45fe1-5c5d-4a41-99a4-0b153e1b078a)

**Comment by bennothommo** [comment]
Fixed as of https://github.com/wintercms/wn-builder-plugin/commit/ea214a225a53f5e631e57231cdf8efa1e62596b8.
