### ISSUE TITLE
The "start creating a plugin" modal's iconpicker select2 is hidden behind the modal

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/wn-builder-plugin#66]
On the Builder page, clicking on "start creating a plugin" and trying to uyse the icon picker will reveal the select2 field, but it will appear behind the modal and the page's "shadow" effect. Setting the generated select2 container's z-index to 5070 or above puts it back on top of the modal (because the modal is set to a z-index of 5070).
![image](https://github.com/wintercms/wn-builder-plugin/assets/104367522/6709ee5a-8301-4130-9cb4-0df47c691e9d)
![image](https://github.com/wintercms/wn-builder-plugin/assets/104367522/68442320-cadd-4d72-8a05-58116ff274d1)

**Comment by LukeTowers** [comment]
This could also just be switched to use the IconPicker FormWidget built into the Winter core now, but I agree that the z-index issue should be fixed. Could you submit a PR to fix that @nmiyazaki-chapleau?

**Comment by LukeTowers** [comment]
@nmiyazaki-chapleau you can change it here: https://github.com/wintercms/winter/blob/develop/modules/system/assets/ui/less/select.less#L543.

To recompile it you can run `artisan mix:install` and make sure to include the system module in your core package.json and then run `artisan mix:compile --production -p module-system`.

**Comment by bennothommo** [comment]
@LukeTowers it's already been changed to the Icon Picker, just waiting on a new release which I'm working on now - https://github.com/wintercms/wn-builder-plugin/commit/1a9c2f912c14e18631e5ea53ca6b560d43ba8aef.
