### ISSUE TITLE
plugin selection side button is not visible after update 1.2.6 of winter cms

### ISSUE THREAD

**Issue by jackpxyz** [wintercms/wn-builder-plugin#67]
plugin selection option gives error in javascript and plugin selection side button is not visible after update 1.2.6

**Comment by LukeTowers** [comment]
@jackpxyz can you share the error and include a screenshot of the visual issue?

**Comment by jackpxyz** [comment]
error on click "Show the plugins list" button : Uncaught TypeError: can't access property "show", $(...).data(...) is undefined
    addWelcomeTab http://gestion.vado/plugins/winter/builder/assets/js/build-min.js?v2.0.6:506
    jQuery 2
build-min.js:506:95
    addWelcomeTab http://gestion.vado/plugins/winter/builder/assets/js/build-min.js?v2.0.6:506
    jQuery 2


With the new side panel it is not possible to select plugin to modify it

![Screenshot 2024-08-27 at 08-20-59 Builder Winter CMS](https://github.com/user-attachments/assets/8bfc05d0-2777-4122-90af-8d1d95707974)
![Screenshot 2024-08-27 at 08-20-47 Welcome Builder Winter CMS](https://github.com/user-attachments/assets/30109dd1-ec20-4ecd-a88b-c7fdac8d8cea)

**Comment by bennothommo** [comment]
@jackpxyz does it work without the Tailwind UI plugin enabled (ie. the original Backend skin)?

**Comment by jackpxyz** [comment]
I don't have that plugin installed, it stopped working since the update to version 1.2.6 which changed the menu structure

**Comment by bennothommo** [comment]
@jackpxyz your screenshots indicate that you have the Tailwind UI plugin enabled. If you didn't, the navigation would be at the top of the page with a black background. We have not changed the menu structure in a normal Winter CMS installation.

**Comment by jackpxyz** [comment]
![image](https://github.com/user-attachments/assets/139b0ed2-a4db-4608-84bd-df22b69785e9)
![image](https://github.com/user-attachments/assets/15feb58e-2abd-45b6-8a26-2f4f5ededbbb)

**Comment by jackpxyz** [comment]
This is what happened to me after updating, and even though I changed the menu to the top, the side menu to select plugin in the builder does not appear and gives an error in the javascript.

**Comment by jackpxyz** [comment]
I checked the plugins folder and the Tailwind UI plugin was installed and active but it didn't appear in the backend. After deleting it, the backend returned to normal. At some point I had installed it but then I deleted it, I don't know what happened. Thank you very much for the help and sorry for the inconvenience. Regards.
